# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [master, main, autodesk]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

concurrency:
  group: cicd-${{ github.head_ref }}
  # cancel-in-progress: true

env:
  APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
  GITHUB_EVENT: ${{ github.event_name }}
  APPLITOOLS_SERVER_URL : "https://eyesapi.applitools.com"
  APPLITOOLS_BATCH_ID: ${{ github.event.pull_request.head.sha || github.sha }}
  # APPLITOOLS_BRANCH: ${{ github.repository }}/${{ github.head_ref || github.ref_name}}    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Log Git SHA
        run: echo "$GITHUB_SHA" \
          echo $APPLITOOLS_BATCH_ID \
          echo ${{ github.repository }} \
          echo ${{ github.ref_name }} \
          echo ${{ github.event_name}} \


      - name: Notify Applitools
        if: github.event_name != 'pull_request'
        run: curl -L -d '' -X POST "${{env.APPLITOOLS_SERVER_URL}}/api/Externals/github/push?apiKey=${{ env.APPLITOOLS_API_KEY }}&CommitSha=${{ env.APPLITOOLS_BATCH_ID }}&BranchName=${{ github.repository }}/${{ github.head_ref || github.ref_name}}"


      - name: Install
        run: npm ci

      - name: Tests
        run: |
          echo $APPLITOOLS_BRANCH_NAME
          echo "autodesk"
          npx eyes-storybook
